version: '3'

services:
  frontend:
    build: ./frontend
    container_name: node-docker-frontend
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    command: serve -s build -l 3000

  api:
    build: ./api
    container_name: node-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://api-service.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
  
  auth:
    build: ./auth
    container_name: node-docker-auth
    command: npm run start
    restart: unless-stopped
    # ports:
    #   - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://node-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db
  
  auth_db:
    image: mongo:latest
    container_name: node-docker-auth_db
    volumes:
      - mongodb_auth:/data/db
  
  api_db:
    image: mongo:latest
    container_name: node-docker-api_db
    volumes:
      - mongodb_api:/data/db
  
  nginx:
    image: nginx:stable-alpine
    container_name: node-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend


volumes:
  mongodb_api:
  mongodb_auth:
